language: php

php:
    - '5.3'
    - '5.4'
    - '5.5'
    - '5.6'
    - '7.0'
    - hhvm
    - nightly

matrix:
    fast_finish: true
    allow_failures:
        - php: nightly

before_install:
    - phpenv config-rm xdebug.ini || true
    - composer config --global github-oauth.github.com $GITHUB_TOKEN
install: composer install --prefer-dist --no-progress --no-interaction --optimize-autoloader --ignore-platform-reqs
script: scripts/travis

env:
    global:
        - ELOQUENT_PUBLISH_VERSION=7.0
        - secure: "IdOEyZWIhJ/6Cgv9kFbRj2InMG5XFVPWbvF1bDFU5UnWPVmcaCpwz6Ez0NyGUXDAIf48s6St3li+nQoZV+vbaVJ5vshEglpvWepM/4HNzEjGOYLLhjSuMKLHhvqfUP0I121FfIrgyD8otbf4LbCbksgEheA3QMgrRSyYi5gzu8Y="

cache:
    directories:
        - $HOME/.composer

sudo: false
